### ISSUE TITLE
Is it necessary to unsubscribe before subscribing with new parameters?

### ISSUE THREAD

**Issue by derwaldgeist** [green-coder/unity3d-ddp-client#10]
For a location-based application, we have to update the subscriptions frequently, i.e. every time a user moves significantly. Is it necessary to unsubscribe in this case before subscribing to the same publication, but with other parameters? Or is it sufficient to just re-subscribe, as it is done in a regular Meteor client?

In the latter case: what happens to event handlers that have been registered on the previous subscription? Will they be automatically purged?

**Comment by green-coder** [comment]
This library is doing nothing more than implementing a communication protocol.

I might be wrong, but your question seems to be related to Meteor's usage and strategy, I think it should be asked on the Meteor forum instead.
