### ISSUE TITLE
Merge with my code?

### ISSUE THREAD

**Issue by brean** [green-coder/unity3d-ddp-client#5]
Hi @green-coder ,

based on your code I created a DDP-Client implementation that uses UWP for Hololens (see [here](https://github.com/brean/csharp-ddp-client) ). Because this fork did not work with Unity I thought it was best to keep it as separated repo.

However, I just finished a more general version that does not use websocket-sharp but System.Net ClientWebSocket for Unity instead, if you use the experimental .Net 4.6 as well as UWP if it is build for it.
So instead of doing my own thing I could merge this with your code again and present a pull request, maybe as a special branch because it requires 4.6. For the older .Net that is used for most Unity Projects you still need a 3rd-party lib like websocket-sharp.

What do you think?

**Comment by green-coder** [comment]
Thank you for your contribution, and welcome. I am fine for having it merged as a different branch. It will help users find what they need.

Ideally, this branch should be mentioned in the README.md. Do you want to do it?

**Comment by brean** [comment]
Yeah, I can provide you a pull request.

During development I ignored the local-db (I am handling data storage outside). I use Newtonsoft.Json to parse the json-string into typed classes. I am not sure if it should be the way to go to create those typed classes (e.g. using [quicktype](https://quicktype.io/)) or use [JSONObject](https://github.com/green-coder/unity3d-ddp-client/blob/master/unity-project/Assets/3rd%20party/JSONObject/JSONObject.cs) like you did instead.

When I switched to pure UWP I used its [JsonObject](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject), but I don't see now why it shouldn't work with UWP. Because JavaScript also does not type the data using JSONObject looks like the right way to go here. Do you think we should use JSONObject or do you know some other solution?

**Comment by green-coder** [comment]
I wrote this project a long time ago with the only goal of having things working. I did not ask myself many questions about which dependencies to use.

I suggest you to go ahead with your own decision, I will just review if it works and then accept the PR. Technically, you are the one in charge as I am not actively maintaining this project.

**Comment by brean** [comment]
[I am finally done](https://github.com/brean/unity3d-ddp-client/tree/Net46-and-UWP). I can only create a pull request for your master branch, so can you please create a new branch?

As you can see, I replaced some stuff with its .Net 4.6 counterparts. I use the new [async-await](http://www.stevevermeulen.com/index.php/2017/09/using-async-await-in-unity3d-2017/) instead of the CoroutineHelper from util. You need to call "ddpConnection.Connect" manually now after you setup the event listeners. I deleted the ConcurrentQueue (I figured out that there is an implementation of it in .Net 4.6 but I also handle the messages when they come from the server directly, instead of queuing them.

Instead of waiting for a call you always need to set the OnResult-Event now because when I call "Call" it only waits until the data has been send and not until an answer has been received. I don't think it would be better to implement a queue and wait until the answer gets handled because if the answer never arrives (e.g. the client gets disconnected) it will wait forever.

As I guessed the [JSONObject from @mtschoen](https://github.com/mtschoen/JSONObject) works with UWP and .Net 4.6. I updated it to the latest version that has some bugfixes and [can now be enumerated](https://github.com/mtschoen/JSONObject/commit/c259ed972c613f915803da3485a9cf59c6cc47c3). 

I also updated the meteor server project and added some Unity UI for the examples. 

Known issue: There seems to be a problem with the .Net ClientWebSocket, I repored it in the [Unity forum](https://forum.unity.com/threads/clientwebsocket-connectasync-freezes-on-3rd-try.508741/) as well as I contacted [the Microsoft support](https://answers.microsoft.com/en-us/windows/forum/windows_other-networking/clientwebsocket-for-net-46-experimental-for-the/39b0676b-0894-4d19-8cb9-f0a6c2dbe053). (The UWP-implementation does not have this problem)

**Comment by green-coder** [comment]
Awesome. I will pull your changes in the new 'dev' branch soon (hopefully tonight) and let you know.

Thanks again for contributing to this project and share your work with everybody.

**Comment by green-coder** [comment]
Hi. I added you as collaborator on this project. You now have the direct push access.
