### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by derwaldgeist** [green-coder/unity3d-ddp-client#9]
Is this repo still being maintained? Since the last commit was one year ago, I am wondering if that's either because the code is stable or because it has been abandoned. :-)

**Comment by brean** [comment]
Well, kinda both. I changed the industry from augmented reality to robotics so I only work with unity in my free time. Feel free to test and update to the newest unity and meteor version.

**Comment by derwaldgeist** [comment]
Thanks for the info. I could not get it to work, though. The sample Unity client won't connect to the server.

**Comment by green-coder** [comment]
The code was/is stable, that's the whole world around which is not :-)

I also don't have time to maintain it as I am not using Meteor anymore. PR are welcome.

**Comment by derwaldgeist** [comment]
Works for me now, the error was on my side. Thanks.
